[package]
name = "maxgus-keys"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true
description = "Emacs key notation, key sequences and keymaps."

[lints]
workspace = true

[dependencies]
crossterm = "0.29.0"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
