//! Installing tree-sitter grammars.
//!
//! The editor colours eleven languages out of the box and can load more from
//! shared libraries a package manager installed. This is the third way: for
//! a language with no grammar anywhere, fetch the one tree-sitter's own wiki
//! lists, build it, and put it where the editor looks.
//!
//! # Nothing happens without an answer
//!
//! Installing means cloning a repository, running a C compiler over it and
//! loading the result into this process. That is a great deal of trust, so
//! it is asked for twice and never assumed:
//!
//! 1. Opening a file in a language with no grammar asks whether to look one
//!    up — which is the only thing "yes" agrees to, and the only point at
//!    which the network is touched. `grammar-auto-install` turns this
//!    question off; nothing else changes when it is off.
//! 2. Once the list has been read, a second question names the exact
//!    repository that would be cloned and compiled. Several candidates make
//!    that a menu instead, which is the same question with more answers.
//!
//! Saying no to the first question is remembered for the session, so a file
//! being edited is not asked about again on every pause in typing.
//!
//! `M-x install-grammar` is the same machinery without the first question:
//! the menu of every parser there is, for choosing one deliberately.

use crate::{
    MinibufferKind, Result, command,
    command::{Args, Registry},
    editor::Editor,
    task::Task,
};

/// Where the log of an install is shown.
pub const INSTALL_BUFFER_NAME: &str = "*Grammar install*";

pub fn register(registry: &mut Registry) {
    registry.register_all(&[
        command!(
            "install-grammar",
            "Choose a tree-sitter parser to fetch, build and install.",
            install_grammar
        ),
        command!(
            "install-grammar-for-buffer",
            "Install a grammar for this buffer's language.",
            install_grammar_for_buffer
        ),
        command!(
            "refresh-grammar-list",
            "Fetch the list of tree-sitter parsers again.",
            refresh_grammar_list
        ),
    ]);
}

/// `M-x install-grammar`: the whole list, to pick from.
///
/// Re-entered with the picked line, which is looked up in the list this
/// editor fetched rather than parsed out of the text — the label is
/// generated by [`maxgus_syntax::Parser::label`], so nothing the user typed
/// decides what gets cloned.
fn install_grammar(editor: &mut Editor, args: &Args) -> Result<()> {
    let Some(answer) = args.input.clone() else {
        editor.message("Fetching the list of parsers...");
        editor.spawn(Task::GrammarCatalog {
            refresh: false,
            language: None,
        });
        return Ok(());
    };
    // One candidate is confirmed rather than picked, and the answer to that
    // question is `yes` rather than the line it stands for. Nothing else
    // sets this, and it is taken as it is read.
    if let Some(parser) = editor.grammar_pending.take() {
        if !answer.trim().eq_ignore_ascii_case("yes") {
            let language = editor.grammar_offer.take().unwrap_or(parser.name);
            editor.grammars_declined.insert(language.clone());
            editor.message(format!("Nothing installed for {language}"));
            return Ok(());
        }
        return start(editor, &parser);
    }
    if answer == SKIP {
        return decline(editor);
    }
    install_chosen(editor, &answer)
}

/// The row at the bottom of the menu that installs nothing, so a menu has
/// a way out that is not `C-g`.
const SKIP: &str = "skip  —  install nothing";

/// The offer refused, and remembered as refused.
fn decline(editor: &mut Editor) -> Result<()> {
    match editor.grammar_offer.take() {
        Some(language) => {
            editor.grammars_declined.insert(language.clone());
            editor.message(format!(
                "Nothing installed. M-x install-grammar-for-buffer asks again for {language}."
            ));
        }
        None => editor.message("Nothing installed"),
    }
    Ok(())
}

/// The buffer's own language: the command the offer re-enters, and a useful
/// one to run by hand when the offer was declined earlier.
fn install_grammar_for_buffer(editor: &mut Editor, args: &Args) -> Result<()> {
    let Some(language) = editor
        .grammar_offer
        .clone()
        .or_else(|| editor.current_buffer().language().map(str::to_string))
    else {
        editor.error("This buffer has no language, so there is nothing to install");
        return Ok(());
    };
    let Some(answer) = args.input.clone() else {
        editor.grammar_offer = Some(language.clone());
        editor.prompt_for(
            "install-grammar-for-buffer",
            MinibufferKind::YesNo,
            format!("No grammar for {language}. Look one up and install it? (yes or no) "),
            "",
            Vec::new(),
        );
        return Ok(());
    };
    editor.grammar_offer = None;
    if !answer.trim().eq_ignore_ascii_case("yes") {
        // Remembered, or the next pause in typing asks again.
        editor.grammars_declined.insert(language.clone());
        editor.message(format!(
            "Nothing installed. M-x install-grammar-for-buffer asks again for {language}."
        ));
        return Ok(());
    }
    editor.message(format!("Looking for a {language} parser..."));
    editor.spawn(Task::GrammarCatalog {
        refresh: false,
        language: Some(language),
    });
    Ok(())
}

/// `M-x refresh-grammar-list`: the wiki gains parsers, and a week-old cache
/// will not have them.
fn refresh_grammar_list(editor: &mut Editor, _: &Args) -> Result<()> {
    editor.message("Fetching the list of parsers...");
    editor.spawn(Task::GrammarCatalog {
        refresh: true,
        language: None,
    });
    Ok(())
}

/// Starts the install for a line taken out of the menu.
fn install_chosen(editor: &mut Editor, label: &str) -> Result<()> {
    let Some(parser) = editor
        .grammar_catalog
        .iter()
        .find(|p| p.label() == label)
        .cloned()
    else {
        editor.error(format!("`{label}` is not one of the parsers on the list"));
        return Ok(());
    };
    start(editor, &parser)
}

/// Queues the install itself.
fn start(editor: &mut Editor, parser: &maxgus_syntax::Parser) -> Result<()> {
    // The name the editor will look it up as. A grammar picked from the menu
    // is installed under its own name; one being installed for a buffer is
    // installed under the buffer's spelling of it, which is the name the
    // loader will ask for and the symbol it will look up.
    let language = match editor.grammar_offer.take() {
        Some(language) if same_language(&language, &parser.name) => language,
        _ => parser.name.clone(),
    };
    if !parser.abi_is_readable() {
        editor.error(format!(
            "{} is ABI {}, which this build cannot read (it reads {}..={})",
            parser.url,
            parser.abi.unwrap_or_default(),
            maxgus_syntax::MIN_ABI,
            maxgus_syntax::MAX_ABI
        ));
        return Ok(());
    }
    editor.message(format!("Installing {language} from {}...", parser.url));
    editor.spawn(Task::InstallGrammar {
        language,
        url: parser.url.clone(),
    });
    Ok(())
}

/// Two names for the same language, punctuation aside — `c-sharp` here and
/// `c_sharp` in the wiki.
fn same_language(a: &str, b: &str) -> bool {
    a.replace('-', "_")
        .eq_ignore_ascii_case(&b.replace('-', "_"))
}

/// Applies [`crate::TaskResult::GrammarMissing`]: the offer.
///
/// `candidates` empty means a parser for the language exists — the names
/// that ship with the editor say so — but no list has been fetched yet, so
/// there is no repository to name. Then the question is the smaller one:
/// may the list be fetched? Nothing is sent at all for a language nobody
/// has written a parser for, so this is never a question about a `.txt`
/// file.
pub fn offer(
    editor: &mut Editor,
    language: &str,
    candidates: Vec<maxgus_syntax::Parser>,
) -> Result<()> {
    if !editor.settings.grammar_auto_install || editor.grammars_declined.contains(language) {
        return Ok(());
    }
    // A question already on screen is not pushed aside by this one, and a
    // prompt the user is part-way through answering is not stolen.
    if editor.minibuffer.is_active() {
        return Ok(());
    }
    editor.grammar_offer = Some(language.to_string());
    if candidates.is_empty() {
        editor.prompt_for(
            "install-grammar-for-buffer",
            MinibufferKind::YesNo,
            format!("No grammar for {language}. Look one up and install it? (yes or no) "),
            "",
            Vec::new(),
        );
        return Ok(());
    }
    editor.grammar_catalog = candidates.clone();
    choose(editor, language, candidates)
}

/// Asks which parser to install: a question when there is one, a menu when
/// there are several. Either way it names the repository that would be
/// cloned, which is the point at which the user is agreeing to run it.
fn choose(
    editor: &mut Editor,
    language: &str,
    candidates: Vec<maxgus_syntax::Parser>,
) -> Result<()> {
    match candidates.len() {
        1 => {
            let parser = candidates[0].clone();
            let question = format!("Clone {}, build it and load it? (yes or no) ", parser.url);
            editor.grammar_pending = Some(parser);
            editor.prompt_for(
                "install-grammar",
                MinibufferKind::YesNo,
                question,
                "",
                Vec::new(),
            );
            Ok(())
        }
        _ => pick_from(
            editor,
            candidates,
            &format!("Install {language} from (or skip): "),
            true,
        ),
    }
}

/// Applies [`crate::TaskResult::GrammarCatalog`]: the menu, or the one
/// question that names what would be cloned.
pub fn show_catalog(
    editor: &mut Editor,
    language: Option<String>,
    parsers: Vec<maxgus_syntax::Parser>,
    error: Option<String>,
) -> Result<()> {
    if let Some(error) = error {
        editor.error(format!("The list of parsers could not be read: {error}"));
        return Ok(());
    }
    editor.grammar_catalog = parsers;
    let Some(language) = language else {
        return pick_from(
            editor,
            editor.grammar_catalog.clone(),
            "Install parser: ",
            false,
        );
    };
    // Already narrowed to that language and ranked best-first by whoever
    // read the list; this only has to ask about it.
    let candidates = editor.grammar_catalog.clone();
    if candidates.is_empty() {
        editor.grammar_offer = None;
        editor.grammars_declined.insert(language.clone());
        editor.error(format!(
            "No parser called `{language}` on tree-sitter's list. \
             M-x install-grammar shows all of them."
        ));
        return Ok(());
    }
    editor.grammar_offer = Some(language.clone());
    choose(editor, &language, candidates)
}

/// Opens the menu over `parsers`. An offer — a menu the editor opened
/// rather than one asked for — has a row for saying no at the bottom,
/// under the parsers, which are what the menu is for.
fn pick_from(
    editor: &mut Editor,
    parsers: Vec<maxgus_syntax::Parser>,
    prompt: &str,
    offered: bool,
) -> Result<()> {
    if parsers.is_empty() {
        editor.error("The list of parsers came back empty");
        return Ok(());
    }
    let mut labels: Vec<String> = parsers.iter().map(maxgus_syntax::Parser::label).collect();
    if offered {
        labels.push(SKIP.to_string());
    }
    editor.prompt_for("install-grammar", MinibufferKind::Pick, prompt, "", labels);
    Ok(())
}

/// Applies [`crate::TaskResult::GrammarInstalled`].
///
/// The log goes in a buffer whatever happened. An install runs two programs
/// on the user's behalf, and what they said is the only way to find out why
/// one of them did not work.
pub fn installed(
    editor: &mut Editor,
    language: &str,
    summary: &str,
    log: &str,
    failed: bool,
) -> Result<()> {
    if !log.is_empty() {
        let id = match editor.buffers.find_by_name(INSTALL_BUFFER_NAME) {
            Some(id) => {
                editor.replace_buffer_contents(id, log)?;
                id
            }
            None => editor.buffers.create_with_text(INSTALL_BUFFER_NAME, log),
        };
        if let Some(buffer) = editor.buffers.get_mut(id) {
            buffer.set_read_only(true);
        }
    }
    match failed {
        true => editor.error(summary.to_string()),
        false => {
            editor.message(summary.to_string());
            // Every buffer in the language, not just the current one: a
            // project of `.zig` files should all colour at once.
            let ids: Vec<_> = editor
                .buffers
                .ids()
                .iter()
                .copied()
                .filter(|id| {
                    editor.buffers.get(*id).is_some_and(|buffer| {
                        buffer
                            .language()
                            .is_some_and(|l| same_language(l, language))
                    })
                })
                .collect();
            for id in ids {
                editor.request_highlighting(id);
            }
        }
    }
    Ok(())
}
