//! Grammars the editor was not built with.
//!
//! Eleven grammars are compiled in ([`crate::languages`]). This loads more of
//! them from shared libraries at run time — the ones a package manager
//! installs as `libtree-sitter-<language>.so`, which is how Arch, Debian,
//! Fedora, Homebrew and Nix all ship them, and how Neovim and Helix consume
//! them.
//!
//! # Why this module is allowed to write `unsafe`
//!
//! Every other crate in the workspace has `unsafe_code = "forbid"`. This one
//! has `deny`, and the difference is that `deny` can be lifted for a named
//! block. Nothing else in the editor may lift it.
//!
//! The reason is not a shortcut. A tree-sitter grammar is a C library
//! exporting one function, `tree_sitter_<language>`, that returns a pointer
//! to a `TSLanguage`. Getting from a path on disk to that pointer is three
//! operations, and none of them can be made safe by any wrapper, because
//! each one asserts something about a file that only the person who put it
//! there can know:
//!
//! 1. **`Library::new`** runs the library's initialisers. A shared object can
//!    execute arbitrary code the moment it is loaded, before anything asks it
//!    for a symbol. No API can promise it will not.
//! 2. **`Library::get`** looks up a symbol and hands back a value of whatever
//!    type the caller asked for. The linker does not record types; if the
//!    symbol is not the function it is claimed to be, the mistake surfaces as
//!    a call through a wrong pointer.
//! 3. **`LanguageFn::from_raw`** says that this function really is a grammar
//!    entry point generated by the tree-sitter CLI. If it is not, the pointer
//!    it returns is read as a `TSLanguage` regardless.
//!
//! So the safety of this is not a property of the code — it is a property of
//! what the user points it at. Which is exactly why loading one is
//! **opt-in**. Two directories can be searched and no others:
//!
//! - the ones a configuration file names, which the user wrote down; and
//! - the one the editor installs into itself ([`crate::install`]), which
//!   holds nothing except grammars the user was asked about by name and
//!   agreed to.
//!
//! The editor still never goes looking anywhere else, and still never
//! installs anything without being told to.
//!
//! # What is checked anyway
//!
//! Being unable to prove something is not a reason to check nothing:
//!
//! - Only files named `libtree-sitter-<language>.so` (or `.dylib`, or
//!   `tree-sitter-<language>.dll`) are opened, in directories the user
//!   named, and only when a buffer's language matches. A directory of
//!   arbitrary libraries is not swept.
//! - The symbol looked up is derived from the language, not from anything in
//!   the file, so a library cannot volunteer what it is called.
//! - The pointer is rejected if it is null.
//! - The ABI version is checked against what this build of tree-sitter can
//!   read, before the grammar is ever used to parse. A grammar built for a
//!   newer or much older tree-sitter is a reported error, not a crash.
//! - Everything is reported by returning an error. A grammar that will not
//!   load leaves the language unhighlighted, which is what it was before.
//!
//! # Why the library is never unloaded
//!
//! A [`Language`] is a pointer *into* the loaded library. Unloading it while
//! a `Language` still exists would leave that pointer dangling, and the
//! borrow checker cannot see the relationship. Rather than tie every
//! `Language` to a lifetime that would have to be threaded through the
//! parser, the tree and the query, a library that loads successfully is
//! leaked and stays mapped until the process exits. Grammars are a handful of
//! files loaded once; the memory is bounded by how many languages are opened,
//! and the alternative is a lifetime running through most of this crate.

use crate::languages::SyntaxLanguage;
use std::path::{Path, PathBuf};
use tree_sitter::Language;

/// What went wrong looking for or opening a grammar.
#[derive(Debug, thiserror::Error)]
pub enum GrammarError {
    #[error("no library named {file} in {}", .searched.join(", "))]
    NotFound { file: String, searched: Vec<String> },
    #[error("{path} would not load: {source}")]
    Library {
        path: String,
        source: libloading::Error,
    },
    #[error("{path} has no `{symbol}` in it, so it is not a {language} grammar")]
    NoSymbol {
        path: String,
        symbol: String,
        language: String,
    },
    #[error("{path} returned no grammar")]
    NoGrammar { path: String },
    #[error(
        "{path} was built for tree-sitter ABI {found}; this build reads {}..={}",
        tree_sitter::MIN_COMPATIBLE_LANGUAGE_VERSION,
        tree_sitter::LANGUAGE_VERSION
    )]
    Abi { path: String, found: usize },
    #[error("no highlights query for {language}: looked in {}", .searched.join(", "))]
    NoQuery {
        language: String,
        searched: Vec<String>,
    },
    #[error("{path} could not be read: {source}")]
    Query {
        path: String,
        source: std::io::Error,
    },
}

/// Where to look for grammars, and for the queries that colour them.
///
/// Empty by default, and empty means nothing is ever loaded. Two things fill
/// it: a `grammars` block in the configuration, and the directory the editor
/// installs into — which is added by whoever builds this, and holds only
/// what the user agreed to install. Nothing else is searched.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Search {
    /// Directories holding `libtree-sitter-<language>.so` and friends.
    pub libraries: Vec<PathBuf>,
    /// Directories holding `<language>/highlights.scm`.
    pub queries: Vec<PathBuf>,
    /// Grammars named outright, for a file that is not where anything
    /// expects it to be.
    pub named: Vec<Named>,
}

/// One `grammar "go" library="…" queries="…"` from the configuration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Named {
    pub language: String,
    pub library: PathBuf,
    /// The `highlights.scm` to colour it with. Without one the search
    /// directories are tried, as they are for a discovered grammar.
    pub queries: Option<PathBuf>,
}

impl Search {
    pub fn is_empty(&self) -> bool {
        self.libraries.is_empty() && self.named.is_empty()
    }
}

/// The file a grammar for `language` would be in, on this platform.
///
/// Unix packages them as `libtree-sitter-<language>.so`; macOS as `.dylib`;
/// Windows drops the `lib` prefix. Both Unix spellings are tried everywhere
/// because a hand-built grammar often lands with the other one.
///
/// Each spelling is tried for each way the language's punctuation can be
/// written, because the two ends disagree: a `.cs` file is `c-sharp` here
/// and the grammar that colours it calls itself `c_sharp`. The name this
/// editor uses comes first, so `library_names(l)[0]` is still the file an
/// install should write.
pub fn library_names(language: &str) -> Vec<String> {
    spellings(language)
        .into_iter()
        .flat_map(|language| match cfg!(target_os = "windows") {
            true => vec![
                format!("tree-sitter-{language}.dll"),
                format!("libtree-sitter-{language}.dll"),
            ],
            false => vec![
                format!("libtree-sitter-{language}.so"),
                format!("libtree-sitter-{language}.dylib"),
                format!("tree-sitter-{language}.so"),
                format!("tree-sitter-{language}.dylib"),
            ],
        })
        .collect()
}

/// The ways a language's name is punctuated, the given one first.
///
/// Grammar authors use `_` and this editor names a language after its file
/// extension, so both turn up. Nothing else about the name is guessed.
fn spellings(language: &str) -> Vec<String> {
    let mut names = vec![language.to_string()];
    for other in [language.replace('-', "_"), language.replace('_', "-")] {
        if !names.contains(&other) {
            names.push(other);
        }
    }
    names
}

/// The symbol a grammar for `language` exports.
///
/// Hyphens in a language name are underscores in a C identifier, which is
/// what makes `tree-sitter-c-sharp` export `tree_sitter_c_sharp`.
pub fn entry_point(language: &str) -> String {
    format!("tree_sitter_{}", language.replace(['-', '.'], "_"))
}

/// Finds and loads the grammar for `language`, with the query to colour it.
pub fn load(language: &str, search: &Search) -> Result<SyntaxLanguage, GrammarError> {
    let named = search.named.iter().find(|n| n.language == language);
    let path = match named {
        Some(named) => named.library.clone(),
        None => find_library(language, &search.libraries)?,
    };
    let grammar = open(&path, language)?;
    let query = match named.and_then(|n| n.queries.clone()) {
        Some(path) => read_query(&path)?,
        None => find_query(language, &search.queries)?,
    };
    Ok(SyntaxLanguage {
        name: language.to_string(),
        language: grammar,
        highlights: query.into(),
    })
}

/// The first file in `directories` that could be a grammar for `language`.
fn find_library(language: &str, directories: &[PathBuf]) -> Result<PathBuf, GrammarError> {
    let names = library_names(language);
    for directory in directories {
        for name in &names {
            let candidate = directory.join(name);
            if candidate.is_file() {
                return Ok(candidate);
            }
        }
    }
    Err(GrammarError::NotFound {
        file: names[0].clone(),
        searched: directories.iter().map(|p| display(p)).collect(),
    })
}

/// `<directory>/<language>/highlights.scm`, which is where every
/// distribution and Neovim itself puts them.
fn find_query(language: &str, directories: &[PathBuf]) -> Result<String, GrammarError> {
    for directory in directories {
        for spelling in spellings(language) {
            let candidate = directory.join(spelling).join("highlights.scm");
            if candidate.is_file() {
                return read_query(&candidate);
            }
        }
    }
    Err(GrammarError::NoQuery {
        language: language.to_string(),
        searched: directories.iter().map(|p| display(p)).collect(),
    })
}

fn read_query(path: &Path) -> Result<String, GrammarError> {
    std::fs::read_to_string(path).map_err(|source| GrammarError::Query {
        path: display(path),
        source,
    })
}

/// Opens one library and takes the grammar out of it.
///
/// The three `unsafe` operations of this module are here and nowhere else.
/// Each says what has to be true for it to be sound, and what is done to
/// make that more likely — which is never the same as making it certain, for
/// the reasons in the module documentation.
fn open(path: &Path, language: &str) -> Result<Language, GrammarError> {
    let symbol = entry_point(language);

    // SAFETY: loading a shared object runs whatever initialisers it has, so
    // this is only sound if the file is one the user meant to run. That
    // cannot be checked here and is not pretended to be: nothing reaches
    // this function unless a configuration file named the directory it came
    // from, and the file is named `libtree-sitter-<language>` for a language
    // a buffer is actually in. The editor never discovers grammars by
    // itself, and never opens a library for a language nothing is written
    // in.
    #[allow(unsafe_code)]
    let library =
        unsafe { libloading::Library::new(path) }.map_err(|source| GrammarError::Library {
            path: display(path),
            source,
        })?;

    // The library outlives every `Language` taken out of it, because it is
    // never dropped. See "Why the library is never unloaded" above.
    let library: &'static libloading::Library = Box::leak(Box::new(library));

    // SAFETY: `get` returns the symbol as whatever type is asked for, and
    // the linker records no types to check that against — so this is sound
    // only if `tree_sitter_<language>` really is a
    // `unsafe extern "C" fn() -> *const ()`. Two things make that so: the
    // signature is the one every grammar the tree-sitter CLI generates has
    // had for its whole existence, and the name is derived from the language
    // the buffer is in rather than read out of the file, so a library cannot
    // offer a differently-shaped function under this name. A file that does
    // not export it at all is an error rather than undefined behaviour,
    // which is the case this catches.
    #[allow(unsafe_code)]
    let entry: libloading::Symbol<'static, unsafe extern "C" fn() -> *const ()> =
        unsafe { library.get(symbol.as_bytes()) }.map_err(|_| GrammarError::NoSymbol {
            path: display(path),
            symbol: symbol.clone(),
            language: language.to_string(),
        })?;

    // SAFETY: `from_raw` asserts that this function is a grammar entry point
    // generated by the tree-sitter CLI — that calling it returns a pointer to
    // a `TSLanguage` laid out the way this version of tree-sitter expects.
    // Nothing in the file says so. What is done instead is to call it and
    // then refuse the result unless it survives two checks that a wrong
    // pointer is very unlikely to survive: it must not be null, and the ABI
    // version it reports must be one this build of tree-sitter can read.
    // Both are below, and both happen before the grammar is used to parse
    // anything.
    #[allow(unsafe_code)]
    let grammar = Language::new(unsafe { tree_sitter_language::LanguageFn::from_raw(*entry) });

    // A grammar function that returned nothing. `Language::new` has already
    // stored the null; it is not dereferenced before this returns.
    if grammar.node_kind_count() == 0 {
        return Err(GrammarError::NoGrammar {
            path: display(path),
        });
    }
    // Built against a tree-sitter this one cannot read. The parser would
    // refuse it later with a less helpful message.
    let abi = grammar.abi_version();
    if !(tree_sitter::MIN_COMPATIBLE_LANGUAGE_VERSION..=tree_sitter::LANGUAGE_VERSION)
        .contains(&abi)
    {
        return Err(GrammarError::Abi {
            path: display(path),
            found: abi,
        });
    }
    Ok(grammar)
}

fn display(path: &Path) -> String {
    path.display().to_string()
}

/// What [`Grammars::ready`] found without going to the disk.
#[derive(Debug)]
pub enum Ready {
    /// Here it is: compiled in, or loaded earlier.
    Have(SyntaxLanguage),
    /// There is none, and looking again would not change that.
    Absent,
    /// It has not been looked for yet. [`load`] it — off the runtime — and
    /// hand the answer back to [`Grammars::remember`].
    MustLoad(Search),
}

/// Every grammar this editor can reach: the ones compiled in, and the ones
/// a configuration file pointed it at.
///
/// Loads are attempted once per language and remembered either way. A
/// grammar that failed is not tried again on the next keystroke — the pause
/// before re-highlighting comes round every time typing stops, and a
/// missing file would be looked for on every one of them.
#[derive(Debug, Default)]
pub struct Grammars {
    search: Search,
    /// What came of asking for each language, whether it worked or not.
    tried: std::collections::HashMap<String, Result<SyntaxLanguage, String>>,
}

impl Grammars {
    pub fn new(search: Search) -> Grammars {
        Grammars {
            search,
            tried: std::collections::HashMap::new(),
        }
    }

    /// What is already known about `language`, without touching the disk.
    ///
    /// A compiled-in grammar always wins. A library on disk cannot quietly
    /// replace one the editor was built with and tested against — being able
    /// to would turn a configuration mistake into eight languages that
    /// suddenly highlight differently.
    ///
    /// Deliberately not a method that loads: opening a library reads from
    /// the disk and runs the library's initialisers, both of which block.
    /// The caller decides where that happens, which for the editor means
    /// `spawn_blocking` and never the runtime.
    pub fn ready(&self, language: &str) -> Ready {
        if let Some(built_in) = crate::languages::compiled_in(language) {
            return Ready::Have(built_in);
        }
        if self.search.is_empty() {
            return Ready::Absent;
        }
        match self.tried.get(language) {
            Some(Ok(grammar)) => Ready::Have(grammar.clone()),
            Some(Err(_)) => Ready::Absent,
            None => Ready::MustLoad(self.search.clone()),
        }
    }

    /// Records what came of a load, so it is attempted once rather than on
    /// every pause in typing.
    pub fn remember(&mut self, language: &str, outcome: Result<SyntaxLanguage, GrammarError>) {
        self.tried.insert(
            language.to_string(),
            outcome.map_err(|error| error.to_string()),
        );
    }

    /// Forgets what came of asking for `language`, so the next buffer in it
    /// looks again.
    ///
    /// This is what an install needs. A language is tried once and the
    /// answer kept — including "there is no such file" — so without this the
    /// grammar just installed would not be looked for until the editor was
    /// restarted.
    pub fn forget(&mut self, language: &str) {
        self.tried.remove(language);
    }

    /// Why `language` has no grammar, for the report that says so. `None`
    /// when it was never asked for, or when it worked.
    pub fn failure(&self, language: &str) -> Option<&str> {
        match self.tried.get(language) {
            Some(Err(why)) => Some(why),
            _ => None,
        }
    }

    /// The languages loaded from disk, in the order they are named.
    pub fn loaded(&self) -> Vec<&str> {
        let mut names: Vec<&str> = self
            .tried
            .iter()
            .filter(|(_, outcome)| outcome.is_ok())
            .map(|(name, _)| name.as_str())
            .collect();
        names.sort_unstable();
        names
    }

    /// The languages that were asked for and would not load, with why.
    pub fn failures(&self) -> Vec<(&str, &str)> {
        let mut failed: Vec<(&str, &str)> = self
            .tried
            .iter()
            .filter_map(|(name, outcome)| match outcome {
                Err(why) => Some((name.as_str(), why.as_str())),
                Ok(_) => None,
            })
            .collect();
        failed.sort_unstable();
        failed
    }

    pub fn search(&self) -> &Search {
        &self.search
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_language_names_the_file_its_platform_would_have() {
        let names = library_names("go");
        assert!(names.iter().all(|n| n.contains("go")));
        match cfg!(target_os = "windows") {
            true => assert!(names.iter().any(|n| n.ends_with(".dll"))),
            false => {
                assert!(names.contains(&"libtree-sitter-go.so".to_string()));
                assert!(names.iter().any(|n| n.ends_with(".dylib")));
            }
        }
    }

    #[test]
    fn a_hyphenated_language_asks_for_a_c_identifier() {
        // `tree-sitter-c-sharp` exports `tree_sitter_c_sharp`. Asking for
        // the hyphenated spelling finds nothing and reads as a missing
        // grammar rather than as the naming rule it is.
        assert_eq!(entry_point("c-sharp"), "tree_sitter_c_sharp");
        assert_eq!(entry_point("go"), "tree_sitter_go");
        assert_eq!(
            entry_point("embedded.template"),
            "tree_sitter_embedded_template"
        );
    }

    #[test]
    fn nothing_is_searched_until_somewhere_is_named() {
        let search = Search::default();
        assert!(search.is_empty(), "the default must look nowhere");
        let error = load("go", &search).expect_err("nothing to find");
        assert!(
            matches!(error, GrammarError::NotFound { .. }),
            "got {error:?}"
        );
    }

    #[test]
    fn a_missing_library_is_reported_with_where_it_was_looked_for() {
        let search = Search {
            libraries: vec![PathBuf::from("/nowhere/at/all")],
            ..Default::default()
        };
        let error = load("go", &search).expect_err("nothing to find");
        let said = error.to_string();
        assert!(said.contains("libtree-sitter-go"), "got `{said}`");
        assert!(said.contains("/nowhere/at/all"), "got `{said}`");
    }

    #[test]
    fn a_file_that_is_not_a_library_is_an_error_rather_than_a_crash() {
        let directory = std::env::temp_dir().join("maxgus-not-a-grammar");
        std::fs::create_dir_all(&directory).unwrap();
        let path = directory.join(library_names("wombat")[0].clone());
        std::fs::write(&path, b"this is not an ELF file").unwrap();
        let search = Search {
            libraries: vec![directory.clone()],
            ..Default::default()
        };
        let error = load("wombat", &search).expect_err("it is not a library");
        assert!(
            matches!(error, GrammarError::Library { .. }),
            "got {error:?}"
        );
        std::fs::remove_file(&path).ok();
    }

    /// A real shared library that is not a grammar: the C library, which
    /// every Unix has and which certainly does not export
    /// `tree_sitter_wombat`.
    #[test]
    #[cfg(target_os = "linux")]
    fn a_library_without_the_symbol_is_refused() {
        let Some(libc) = ["/usr/lib/libm.so.6", "/lib/x86_64-linux-gnu/libm.so.6"]
            .into_iter()
            .map(PathBuf::from)
            .find(|p| p.is_file())
        else {
            eprintln!("skipping: no libm to point at");
            return;
        };
        let search = Search {
            named: vec![Named {
                language: "wombat".into(),
                library: libc,
                queries: None,
            }],
            ..Default::default()
        };
        let error = load("wombat", &search).expect_err("libm is not a grammar");
        assert!(
            matches!(error, GrammarError::NoSymbol { .. }),
            "got {error:?}"
        );
    }
}
